// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummy-Web-Key-For-Development',
    appId: '1:123456789:web:dummy-web-app-id',
    messagingSenderId: '123456789',
    projectId: 'mobi-party-link-dev',
    authDomain: 'mobi-party-link-dev.firebaseapp.com',
    storageBucket: 'mobi-party-link-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjEUKBS4J4eUZRJFwI7ghahts8Fq-0q0',
    appId: '1:225781461439:android:0456c7d4ecaf2e0c92b10a',
    messagingSenderId: '225781461439',
    projectId: 'mobi-party-link',
    storageBucket: 'mobi-party-link.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-FvR00wzx5TRozw094sNQeMA6d0iF5w',
    appId: '1:225781461439:ios:d6356290adf828d192b10a',
    messagingSenderId: '225781461439',
    projectId: 'mobi-party-link',
    storageBucket: 'mobi-party-link.firebasestorage.app',
    iosBundleId: 'studio.deskmonent.mobipartylink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummy-macOS-Key-For-Development',
    appId: '1:123456789:ios:dummy-macos-app-id',
    messagingSenderId: '123456789',
    projectId: 'mobi-party-link-dev',
    storageBucket: 'mobi-party-link-dev.appspot.com',
    iosBundleId: 'studio.deskmonent.mobipartylink',
  );
}
