class PartyTemplates {
  static const List<Map<String, dynamic>> templates = [
    {
      'name': '서큐버스 레이드',
      'category': '레이드',
      'difficulty': '입문',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 1000,
      'maxPower': 2000,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '서큐버스 레이드',
      'category': '레이드',
      'difficulty': '어려움',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 2000,
      'maxPower': 3000,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '서큐버스 레이드',
      'category': '레이드',
      'difficulty': '매우어려움',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 3000,
      'maxPower': 4000,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '글라스기브넨 레이드',
      'category': '레이드',
      'difficulty': '입문',
      'maxMembers': 8,
      'requireJob': true,
      'requirePower': true,
      'minPower': 1500,
      'maxPower': 2500,
      'requireJobCategory': true,
      'tankLimit': 2,
      'healerLimit': 2,
      'dpsLimit': 4,
    },
    {
      'name': '글라스기브넨 레이드',
      'category': '레이드',
      'difficulty': '어려움',
      'maxMembers': 8,
      'requireJob': true,
      'requirePower': true,
      'minPower': 2500,
      'maxPower': 3500,
      'requireJobCategory': true,
      'tankLimit': 2,
      'healerLimit': 2,
      'dpsLimit': 4,
    },
    {
      'name': '글라스기브넨 레이드',
      'category': '레이드',
      'difficulty': '매우어려움',
      'maxMembers': 8,
      'requireJob': true,
      'requirePower': true,
      'minPower': 3500,
      'maxPower': 4500,
      'requireJobCategory': true,
      'tankLimit': 2,
      'healerLimit': 2,
      'dpsLimit': 4,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '입문',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 1200,
      'maxPower': 2200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '어려움',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 2200,
      'maxPower': 3200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '매우어려움',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 3200,
      'maxPower': 4200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '지옥1',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 4200,
      'maxPower': 5200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '지옥2',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 5200,
      'maxPower': 6200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '지옥3',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 6200,
      'maxPower': 7200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '지옥4',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 7200,
      'maxPower': 8200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '지옥5',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 8200,
      'maxPower': 9200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '지옥6',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 9200,
      'maxPower': 10200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
    {
      'name': '마스터 던전 어비스',
      'category': '던전',
      'difficulty': '지옥7',
      'maxMembers': 4,
      'requireJob': true,
      'requirePower': true,
      'minPower': 10200,
      'maxPower': 11200,
      'requireJobCategory': true,
      'tankLimit': 1,
      'healerLimit': 1,
      'dpsLimit': 2,
    },
  ];
}
